pipeline:
  restore-cache:
    image: plugins/s3-cache:1
    pull: true
    endpoint: https://build-cache.codesink.net
    access_key: minio
    secret_key: minio123
    restore: true
    volumes:
      - /var/lib/docker

  docker:
    image: plugins/docker
    repo: justinbarrick/docker-cache
    secrets: [docker_username, docker_password]
    tags: latest
    volumes:
      - /var/lib/docker

  rebuild-cache:
    image: plugins/s3-cache:1
    pull: true
    endpoint: https://build-cache.codesink.net
    access_key: minio
    secret_key: minio123
    rebuild: true
    mount:
      - /var/lib/docker
    volumes:
      - /var/lib/docker
