workspace:
  base: /build
  path: build

pipeline:
  restore-cache:
    image: plugins/s3-cache:1
    endpoint: https://build-cache.codesink.net
    access_key: minio
    secret_key: minio123
    restore: true
    volumes:
      - drone-cache:/build/build/docker

  docker:
    image: plugins/docker
    repo: justinbarrick/docker-cache
    secrets: [docker_username, docker_password]
    tags: latest
    volumes:
      - drone-cache:/var/lib/docker

  rebuild-cache:
    image: plugins/s3-cache:1
    endpoint: https://build-cache.codesink.net
    access_key: minio
    secret_key: minio123
    rebuild: true
    mount:
      - docker/
    volumes:
      - drone-cache:/build/build/docker
