pipeline:
  restore-cache:
    image: plugins/s3-cache:1
    endpoint: https://build-cache.codesink.net
    access_key: minio
    secret_key: minio123
    restore: true
    volumes:
      - drone-cache:/var/lib/docker

  test:
    image: alpine
    commands:
      - ls /var/lib/docker
      - "ls hello/ || :"
      - mkdir hello
      - echo hi > hello/hi
    volumes:
      - drone-cache:/var/lib/docker

  docker:
    image: plugins/docker
    repo: justinbarrick/docker-cache
    secrets: [docker_username, docker_password]
    tags: latest
    volumes:
      - drone-cache:/var/lib/docker

  rebuild-cache:
    image: plugins/s3-cache:1
    endpoint: https://build-cache.codesink.net
    access_key: minio
    secret_key: minio123
    rebuild: true
    mount:
      - /var/lib/docker
      - hello/
    volumes:
      - drone-cache:/var/lib/docker
