apiVersion: v1
kind: Namespace
metadata:
  name: build-cache
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: build-cache
  namespace: build-cache
spec:
  serviceName: build-cache
  replicas: 4
  selector:
    matchLabels:
      app: build-cache
  template:
    metadata:
      labels:
        app: build-cache
    spec:
      containers:
      - name: build-cache
        env:
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
        image: minio/minio:RELEASE.2018-08-25T01-56-38Z
        args:
        - server
        - http://build-cache-0.build-cache.build-cache.svc.cluster.local:9000/data
        - http://build-cache-1.build-cache.build-cache.svc.cluster.local:9000/data
        - http://build-cache-2.build-cache.build-cache.svc.cluster.local:9000/data
        - http://build-cache-3.build-cache.build-cache.svc.cluster.local:9000/data
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: cache-volume
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 20
      volumes:
      - name: cache-volume
        emptyDir:
---
kind: Service
apiVersion: v1
metadata:
  name: build-cache
  namespace: build-cache
spec:
  clusterIP: None
  selector:
    app: build-cache
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: build-cache
  namespace: build-cache
  annotations:
    external-dns.alpha.kubernetes.io/target: "kubernetes.codesink.net."
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-tls-secret: "default/cloudflare"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/proxy-body-size: 1g
spec:
  rules:
    - host: build-cache.codesink.net
      http:
        paths:
          - path: /
            backend:
              serviceName: build-cache
              servicePort: 80
  tls:
    - hosts:
      - build-cache.codesink.net
      secretName: cluster-codesink-origin-ca
